services:
  app:
    build:
      # Use the current directory as the build context
      context: '.'
    ports:
      - '3000:3000'
    volumes:
      - .:/app # Mount the current directory to /app in the container for live code updates
      - blog_volume:/app/node_modules # Use a named volume for node_modules to persist dependencies
    env_file:
      - ./.env.local
    command: 'npm run dev'

volumes:
  blog_volume:
