name: npm test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  npm-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.19]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: 'Run test:react'
        run: npm run test:react
      - name: 'Run test:audit'
        run: npm run test:audit
      - name: 'Run eslint'
        run: npm run eslint
